config/routes.rb
Rails.application.routes.draw do
 root "cities#index"

 get 'login', to: 'sessions#new'
 get 'logout', to: 'sessions#destroy'

  resources :cities
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates_presence_of :name, message: "Пожалуйста, введите название города"
  validates_presence_of :lat, message: "Пожалуйста, обозначьте расположение города на карте"
end

app/models/user.rb
class User < ApplicationRecord
  include ActiveModel::SecurePassword
  has_secure_password
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_valid_user!, except: [:index]

  def current_user
    if !session[:user_id].blank?
      @user ||= User.find(session[:user_id])
    end
  end

  def require_valid_user!
    if current_user.nil?
      flash[:error] = 'Please, logIn'
      redirect_to login_path
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  require 'net/http'
  require 'json'
  def test_connection
    begin
  uri = URI("http://ya.ru")
  req = Net::HTTP::Get.new(uri)
    rescue => e
      @error = e.message
      exception Handling
    end
  end

  def index
    @cities = City.all
  end

  def new

    if session[:isadmin]
      unless @error
    @city = City.new
      end
    else
      redirect_to root_path
    end
    
  end

  def create
    @city = City.new(city_params)
    if @city.save
      flash[:success] = "Object successfully created"
      redirect_to @city
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show
    
    @city = City.find(params[:id])
    begin
    uri = URI("https://api.weather.yandex.ru/v1/forecast?lat=#{@city.lat}&lon=#{@city.lon}")
    req = Net::HTTP::Get.new(uri)

 
    req['X-Yandex-API-Key'] = "a0c21972-3aea-4613-b10b-16b6afd4ea17"

    res = Net::HTTP.start(uri.host) { |http|
    http.request(req)
    }
    info = res.body
    @weather = JSON.parse(info)
  rescue
    
    @cities = City.all
    flash[:error] = "Отсутствует подключение к серверу погоды" #вывод на индексе
    render 'index'
  end
  end
  
  private

  def city_params
    params.require(:city).permit(:id, :name, :lat, :lon)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_valid_user!, except: [:destroy]
def create
  reset_session
  @user = User.find_by(name: session_params[:name])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      session[:name] = @user.name
      session[:isadmin] = @user.isadmin

      flash[:success] = "Добро пожаловать господин #{@user.name}"
      redirect_to root_path
    else
      flash[:error] = "Error, try again, please"
      redirect_to root_path
    end
end

def destroy
  reset_session
end

def view_user
  redirect_to login_path
end


private

def session_params
  params.require(:session).permit(:name,:password,:isadmin)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_valid_user!
  before_action :reset_session

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.isadmin = true

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Вы сосздали аккаунт администратора"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password,:password_confirmation, :isadmin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
 <p id="notice"><%= notice %></p>
<% if session[:isadmin] %>
<p>
<%= link_to 'Добавить город', new_city_path, class: "btn btn-lg btn-primary" %>
</p>
<% end %>
<div class="container-fluid">
<div class="row">
<div class="col-md-12">
<table class="table table-striped">

<% @cities.each do |f| %>
<tr>
<td>
  <%= link_to f.name, f %>
</td>
</tr>
<% end %>
</table>
</div>
</div>
</div>

app/views/cities/new.html.erb
<!-- 
todo:
- Не работает вывод валидации
- Привести фронтенд к нормальному виду
- Не загружается карта с первого раза. Только после обновления страницы
- !!! Вывод названия города из карты, запись названия в slug(Латинское название города)
     -->

<p id="notice"><%= notice %></p>


<%= form_with(model: @city, remote: true) do |f| %>


<% if @city.errors.any? %>
<div id="error_explanation">
<h2><%= plurilize(@city.errors.count, "error") %></h2>

<ul>
<% @city.errors.full_messages.each do |message| %>
<li> <%= message %> </li>
<% end %>
</ul>
</div>
<% end %>

  <%= f.text_field :name  %>
  <%= f.hidden_field :slug %>
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lon %>
  <%= f.submit "Добавить город" %>
<% end %>
<button id="show_map">Показать карту</button>
<body>
    <div id="map" style="width: 600px; height: 400px"></div>
</body>



<script src="https://api-maps.yandex.ru/2.1/?apikey<dcdc212d-82f3-487e-840d-80db4d33c8a2>&lang=ru_RU" type="text/javascript"></script>
 
    



	<style>
        html, body, #map {
            width: 100%; height: 100%; padding: 0; margin: 0;
        }
    </style>


<script type="text/javascript">
$("#show_map").on('click', function(){
location.reload();

});
    // Функция ymaps.ready() будет вызвана, когда
    // загрузятся все компоненты API, а также когда будет готово DOM-дерево.
document.addEventListener("turbolinks:load", function () {

    ymaps.ready(init);
    function init() {
    myMap = new ymaps.Map("map", {
        center: [57.5262, 38.3061], // Углич
        zoom: 11
    }, {
        balloonMaxWidth: 200,
        searchControlProvider: 'yandex#search'
    });

    // Обработка события, возникающего при щелчке
    // левой кнопкой мыши в любой точке карты.
    // При возникновении такого события откроем балун.
    myMap.events.add('click', function (e) {
        if (!myMap.balloon.isOpen()) {
            var coords = e.get('coords');
                $("#city_lat").val(coords[0].toPrecision(6));
                $("#city_lon").val(coords[1].toPrecision(6));

            myMap.balloon.open(coords, {
                contentHeader:'Событие!',
                contentBody:'<p>Координаты города: ' + [
                    coords[0].toPrecision(6),
                    coords[1].toPrecision(6)
                    ].join(', ') + '</p>',
                contentFooter:'<sup>Щелкните еще раз</sup>'
            });
        }
        else {
            myMap.balloon.close();
        }
    });

    
    myMap.events.add('contextmenu', function (e) {
        myMap.hint.open(e.get('coords'), 'Кто-то щелкнул правой кнопкой');
    });
    
    // Скрываем хинт при открытии балуна.
    myMap.events.add('balloonopen', function (e) {
        myMap.hint.close();
    });
    
}
});
</script>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<%= @city.name %>
<br><br><br>  
<%= @weather["fact"]["temp"] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Create a new account using the form below.  All fields are required.</p>

<% if @user.errors.any? %>
  <div class='alert alert-danger'>
    <p>Please correct the following errors:</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <div class='form-group'>
    <%= f.label :Логин %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class='form-group'>
    <%= f.label :Пароль %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :"Подтверждение пароля(еще раз пароль)" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit 'Register', class: 'btn btn-primary' %>
<% end %>

<p class='mt-2'>
  Already have an account? <%= link_to 'Click here to sign in.', login_path %>
</p>